name: CTF Deploy Instance
on:
  workflow_dispatch:
    inputs:
      requester:
        type: string
        description: Email of requester
        required: true
      cftdName:
        type: string
        description: CTF instance prefix (must begin with alphabetic)
        required: true        
      ttl:
        type: choice
        description: Hours until self-destruct
        options:
        - 24
        - 36
        - 48
        - 72
        default: "24"
      customer:
        type: string
        description: Customer
        required: true        
      questionbank:
        type: choice
        description: Select a question bank category
        options:
        - Customer Event
        - Partner Event
        default: "Customer Event"
      size:
        type: choice
        description: Number of participants
        options:
        - 1-15
        - 16-30
        default: "1-15"
permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Deploy CTF Instance
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: main.tf
