name: Apply terraform plan

on:
  workflow_dispatch:
    inputs:
      email:
        type: string
        description: Email of requester
    inputs:
      prefix:
        type: string
        description: CTF instance prefix (must begin with alphabetic)        
      TTL:
        type: choice
        description: Hours until self-destruct
        options:
        - 24
        - 36
        - 48
        - 72
      message:
        required: true
      customerName:
        type: string
        description: Customer      
      questionBank:
        type: choice
        description: Select a question bank category
        options:
        - a
        - b
      participantCount:
        type: choice
        description: Number of participants
        options:
        - 1-15
        - 16-30
        - >31
permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Deploy CTF Instance
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./main.tf
